#!/bin/bash
#SBATCH -o slurm-%j.out
#SBATCH --time=00:01:00
#SBATCH -J test_job
#SBATCH --ntasks-per-node=1
#SBATCH --export=NONE
#SBATCH --mem-bind=local
#SBATCH --nice=10
#SBATCH --mem=10M

# example sbatch script for SLURM
# https://slurm.schedmd.com/sbatch.html
# run with:
# $ sbatch sbatch_example.sh

SLURM_VARS='
SBATCH_MEM_BIND
SBATCH_MEM_BIND_LIST
SBATCH_MEM_BIND_PREFER
SBATCH_MEM_BIND_TYPE
SBATCH_MEM_BIND_VERBOSE
SLURM_ARRAY_TASK_COUNT
SLURM_ARRAY_TASK_ID
SLURM_ARRAY_TASK_MAX
SLURM_ARRAY_TASK_MIN
SLURM_ARRAY_TASK_STEP
SLURM_ARRAY_JOB_ID
SLURM_CHECKPOINT_IMAGE_DIR
SLURM_CLUSTER_NAME
SLURM_CPUS_ON_NODE
SLURM_CPUS_PER_TASK
SLURM_DISTRIBUTION
SLURM_GTIDS
SLURM_JOB_ACCOUNT
SLURM_JOB_ID
SLURM_JOB_CPUS_PER_NODE
SLURM_JOB_DEPENDENCY
SLURM_JOB_NAME
SLURM_JOB_NODELIST
SLURM_JOB_NUM_NODES
SLURM_JOB_PARTITION
SLURM_JOB_QOS
SLURM_JOB_RESERVATION
SLURM_LOCALID
SLURM_MEM_PER_CPU
SLURM_MEM_PER_NODE
SLURM_MEM_PER_NODE
SLURM_NODEID
SLURM_NTASKS
SLURM_NTASKS_PER_CORE
SLURM_NTASKS_PER_NODE
SLURM_NTASKS_PER_SOCKET
SLURM_PACK_SIZE
SLURM_PRIO_PROCESS
SLURM_PROCID
SLURM_PROFILE
SLURM_RESTART_COUNT
SLURM_SUBMIT_DIR
SLURM_SUBMIT_HOST
SLURM_TASKS_PER_NODE
SLURM_TASK_PID
SLURM_TOPOLOGY_ADDR
SLURM_TOPOLOGY_ADDR_PATTERN
SLURMD_NODENAME
'
for item in $SLURM_VARS; do echo "${item}: ${!item:-none}"; done
