# base boilerplat demo template Dockerfile
FROM centos:7

MAINTAINER Stephen M. Kelly

RUN yum update -y

RUN yum install -y wget
RUN yum install -y git
RUN yum install -y make
RUN yum install -y gcc
RUN yum install -y zlib
RUN yum install -y zlib-devel
RUN yum install -y bzip2
RUN yum install -y bzip2-libs
RUN yum install -y bzip2-devel
RUN yum install -y gcc-c++
RUN yum install -y unzip
RUN yum install -y xz-devel
